spring.application.name=gamestore

##Configurar o banco de dados
spring.datasource.url=jdbc:postgresql:postgresql://dpg-d6tvghtm5p6s73bl1e90-a.oregon-postgres.render.com/db_deploy_gs_chronos333
spring.datasource.username=chronos333
spring.datasource.password=MoLnMfPKVdxNICC3N3FqRtcxhgLdBSk4
# obs: nunca colocar senhas em documentos que vao para o github

## Configurações do JPA - hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true

